### ISSUE TITLE
KsanRestoreObject, KsanStorageMove 추가

### ISSUE THREAD

**Issue by HeoKyungseok** [infinistor/ksan#132]
KsanRestoreObject -> GLACIER storage에 저장되어 있는 오브젝트를 STANDARD storage로 이동 시킨다.
KsanStorageMove -> 해당 오브젝트가 STANDARD storage에 저장되어 있으면 GLACIER storage로, CLACIER storage에 저장되어 있으면 STANDARD storage로 이동 시킨다.

**Comment by pspace07** [comment]
아웃라인에 시험 내용 정리하고 공유하여야 함
