### ISSUE TITLE
ksan_install.sh : 저사양 서버에서 All-in-One 설치 문제

### ISSUE THREAD

**Issue by PSPACE-KYS** [infinistor/ksan#134]
* 저사양 서버에서 KSAN 설치 도구로 All-in-One 모드 설치 시 일부 모듈의 상태값이 이상함
  * 테스트 서버 사양 : AMD Opteron(tm) X3216 APU
  * 상기 서버 사양에서 "ksan_install.sh allinone" 명령으로 설치 시 아래 문제가 발생함
    * ksanOSD, ksanGW, ksanLifecycleManager 등 대부분의 모듈의 상태가 "UNKNOWN"으로 출력됨
    * 상기 상태에서 ./ksan service list  명령으로 서비스 상태를 다시 조회하면 이상 없이 "ONLINE"으로 표기됨 
 * 이 문제는 인스톨러의 내부 코드에서 서비스를 재시작한 뒤에 기다리는 시간을 늘리는 방식으로 해결될 것으로 보임

**Comment by jssinn** [comment]
더이상 재현되지 않음
