### ISSUE TITLE
ksanUtility에서 Server / Service / Disk / Diskpool / ksanUser 의 NAME 형식으로 관련 API를 처리할 수 있도록 변경 필요

### ISSUE THREAD

**Issue by jssinn** [infinistor/ksan#60]
기존 Server / Service / Disk / Diskpool / ksanUser ID으로만 관리할 수 있는 ksanUtility를 NAME 형식으로도 관리가 가능하도록 변경해야 함

이 추가 기능 개발은 #59 와 관련됨

**Comment by bkfly2000** [comment]
수정 완료
